In [1]:

import numpy as np

a1 = np.linspace(1, 12, 12).reshape((3, 4))
a2 = np.arange(1, 5)  # [ 1 2 3 4 ]
a3 = a2.reshape((4, 1))
a4 = a1.reshape((3, 1, 4))
print(a1)
print(a2)
print(a3)
print(a4)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[[ 1.  2.  3.  4.]]

 [[ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]]]


In [2]:

print(a1 + a2)
print((a1 + a2).shape)
print(a2 + a3)
print((a2 + a3).shape)
print(a1)
print(a4)
print(a1 + a4)
print((a1 + a4).shape)

[[ 2.  4.  6.  8.]
 [ 6.  8. 10. 12.]
 [10. 12. 14. 16.]]
(3, 4)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
(4, 4)
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[[ 1.  2.  3.  4.]]

 [[ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]]]
[[[ 2.  4.  6.  8.]
  [ 6.  8. 10. 12.]
  [10. 12. 14. 16.]]

 [[ 6.  8. 10. 12.]
  [10. 12. 14. 16.]
  [14. 16. 18. 20.]]

 [[10. 12. 14. 16.]
  [14. 16. 18. 20.]
  [18. 20. 22. 24.]]]
(3, 3, 4)


In [3]:

a1 = np.arange(1, 10 + 1) ** 2
a2 = a1[2:9]  # 얕은 복사
print(a1, a2)
a1[3] = a1[1] + a1[2]  # 원소의 변경
a2[:5:2] = 10_000
# for i in range(len(a1)):
#     print(a1[(i + 1) * -1], end=", ")
print(a1[::-1])
print()

[  1   4   9  16  25  36  49  64  81 100] [ 9 16 25 36 49 64 81]
[  100    81    64 10000    36 10000    13 10000     4     1]



In [4]:
a1 = np.fromfunction(lambda x, y, z: x + y + z, (2, 5, 4), dtype=np.int64)
a2 = a1[:, 1::2, :3]  # 얕은 복사

print(a1)

a2[1, ...] = -1

print(a1)

for ar in a2:
    print(ar)

[[[0 1 2 3]
  [1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]]]
[[[ 0  1  2  3]
  [ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]
  [ 4  5  6  7]]

 [[ 1  2  3  4]
  [-1 -1 -1  5]
  [ 3  4  5  6]
  [-1 -1 -1  7]
  [ 5  6  7  8]]]
[[1 2 3]
 [3 4 5]]
[[-1 -1 -1]
 [-1 -1 -1]]


In [5]:
a1 = np.fromfunction(lambda x, y, z: x + y + z, (2, 5, 4), dtype=np.int64)
a2 = np.arange(1, a1.size / 2 + 1).reshape(1, 5, 4) * 10
print(a1)
print(a2)

[[[0 1 2 3]
  [1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]]]
[[[ 10.  20.  30.  40.]
  [ 50.  60.  70.  80.]
  [ 90. 100. 110. 120.]
  [130. 140. 150. 160.]
  [170. 180. 190. 200.]]]


In [6]:
a3 = np.vstack((a1[0, ...], a2[0, ...]))
print(a3)
a4 = np.hstack((a1[0, ...], a2[0, ...]))
print(a4)
a5 = np.concatenate((a1, a2), 0)
print(a5)
a6 = np.concatenate((a1[0, ...], a2[0, ...]), 0)  # hstack
a7 = np.concatenate((a1[0, ...], a2[0, ...]), 1)  # vstack
print(a6)
print(a7)

[[  0.   1.   2.   3.]
 [  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]
 [130. 140. 150. 160.]
 [170. 180. 190. 200.]]
[[  0.   1.   2.   3.  10.  20.  30.  40.]
 [  1.   2.   3.   4.  50.  60.  70.  80.]
 [  2.   3.   4.   5.  90. 100. 110. 120.]
 [  3.   4.   5.   6. 130. 140. 150. 160.]
 [  4.   5.   6.   7. 170. 180. 190. 200.]]
[[[  0.   1.   2.   3.]
  [  1.   2.   3.   4.]
  [  2.   3.   4.   5.]
  [  3.   4.   5.   6.]
  [  4.   5.   6.   7.]]

 [[  1.   2.   3.   4.]
  [  2.   3.   4.   5.]
  [  3.   4.   5.   6.]
  [  4.   5.   6.   7.]
  [  5.   6.   7.   8.]]

 [[ 10.  20.  30.  40.]
  [ 50.  60.  70.  80.]
  [ 90. 100. 110. 120.]
  [130. 140. 150. 160.]
  [170. 180. 190. 200.]]]
[[  0.   1.   2.   3.]
 [  1.   2.   3.   4.]
 [  2.   3.   4.   5.]
 [  3.   4.   5.   6.]
 [  4.   5.   6.   7.]
 [ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]
 [1

In [7]:
# split
a = np.arange(24).reshape(3, 2, 4)
# b1, b2, b3 = np.vsplit(a, 3)  # 얕은 복사
# b4, b5 = np.hsplit(a, 2)  # 얕은 복사
b1 = a[0, ...]
b2 = a[1, ...]
b3 = a[2, ...]
b4 = a[:, 0, :]
b5 = a[:, 1, :]

print(a)
b1[...] = 100
print(b1, b2, b3, b4, b5, sep="\n\n\n")
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[100 100 100 100]
 [100 100 100 100]]


[[ 8  9 10 11]
 [12 13 14 15]]


[[16 17 18 19]
 [20 21 22 23]]


[[100 100 100 100]
 [  8   9  10  11]
 [ 16  17  18  19]]


[[100 100 100 100]
 [ 12  13  14  15]
 [ 20  21  22  23]]
[[[100 100 100 100]
  [100 100 100 100]]

 [[  8   9  10  11]
  [ 12  13  14  15]]

 [[ 16  17  18  19]
  [ 20  21  22  23]]]


In [8]:

a1 = np.arange(1, 5)
a2 = np.arange(1, 7).reshape((2, 3))
a3 = np.linspace(10, 120, 12).reshape((3, 2, 2))
b1 = a1.T
b2 = a2.transpose()
b2[0] = 100
b3 = np.transpose(a3)

print(a1, a2, a3, b1, b2, b3, sep="\n\n\n")

[1 2 3 4]


[[100   2   3]
 [100   5   6]]


[[[ 10.  20.]
  [ 30.  40.]]

 [[ 50.  60.]
  [ 70.  80.]]

 [[ 90. 100.]
  [110. 120.]]]


[1 2 3 4]


[[100 100]
 [  2   5]
 [  3   6]]


[[[ 10.  50.  90.]
  [ 30.  70. 110.]]

 [[ 20.  60. 100.]
  [ 40.  80. 120.]]]


In [9]:
a1 = np.array([[2, -1, 5], [-5, 2, 2], [2, 1, 3]])
a2 = np.array([[0, 1, 0], [1, 0, 1], [1, 1, 0]])
a3 = np.array([1, -1, 1])
a4 = np.array([1, 0, 1]).reshape((3, 1))

b1 = np.dot(a1, a2)
b2 = a1.dot(a3)
b3 = a1.dot(a4)

print(a1, a2, a3, a4, b1, b2, b3, sep="\n\n\n")

[[ 2 -1  5]
 [-5  2  2]
 [ 2  1  3]]


[[0 1 0]
 [1 0 1]
 [1 1 0]]


[ 1 -1  1]


[[1]
 [0]
 [1]]


[[ 4  7 -1]
 [ 4 -3  2]
 [ 4  5  1]]


[ 8 -5  4]


[[ 7]
 [-3]
 [ 5]]


In [10]:
a1 = np.random.randint(10, size=(3, 3))
a2 = np.linalg.inv(a1)


a3 = np.array([[2, 3], [5, 6]])
a4 = np.array([4, 7])
# a5 = np.linalg.solve(a3, a4)
a5 = np.linalg.inv(a3).dot(a4)
print(a1, a2, a3, a4, a5, sep="\n\n\n")

[[5 1 4]
 [4 2 8]
 [5 7 2]]


[[ 0.33333333 -0.16666667  0.        ]
 [-0.20512821  0.06410256  0.15384615]
 [-0.11538462  0.19230769 -0.03846154]]


[[2 3]
 [5 6]]


[4 7]


[-1.  2.]


In [11]:
a1 = np.arange(360 + 1)
# a2 = np.sin(a1* np.pi/180 )
a2 = np.sin(np.radians(a1))
print(a2)

np.savez_compressed("sin_sample", x=a1, y=a2)

[ 0.00000000e+00  1.74524064e-02  3.48994967e-02  5.23359562e-02
  6.97564737e-02  8.71557427e-02  1.04528463e-01  1.21869343e-01
  1.39173101e-01  1.56434465e-01  1.73648178e-01  1.90808995e-01
  2.07911691e-01  2.24951054e-01  2.41921896e-01  2.58819045e-01
  2.75637356e-01  2.92371705e-01  3.09016994e-01  3.25568154e-01
  3.42020143e-01  3.58367950e-01  3.74606593e-01  3.90731128e-01
  4.06736643e-01  4.22618262e-01  4.38371147e-01  4.53990500e-01
  4.69471563e-01  4.84809620e-01  5.00000000e-01  5.15038075e-01
  5.29919264e-01  5.44639035e-01  5.59192903e-01  5.73576436e-01
  5.87785252e-01  6.01815023e-01  6.15661475e-01  6.29320391e-01
  6.42787610e-01  6.56059029e-01  6.69130606e-01  6.81998360e-01
  6.94658370e-01  7.07106781e-01  7.19339800e-01  7.31353702e-01
  7.43144825e-01  7.54709580e-01  7.66044443e-01  7.77145961e-01
  7.88010754e-01  7.98635510e-01  8.09016994e-01  8.19152044e-01
  8.29037573e-01  8.38670568e-01  8.48048096e-01  8.57167301e-01
  8.66025404e-01  8.74619

In [12]:
a3 = np.load("sin_sample.npz")
print(a3["x"])
print(a3["y"])

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24